# This file is part of project link.developers/ld-node-camera-avt-2.
# It is copyrighted by the contributors recorded in the version control history of the file,
# available from its original location https://gitlab.com/link.developers/ld-node-camera-avt-2.
#
# SPDX-License-Identifier: MPL-2.0

package:
  name: "ld-node-camera-avt-2"
  version: {{ BUILD_VERSION }}

source:
  git_url: ../

build:
  skip: true  # [aarch64]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ld-cmake-tools
    - flatc

  host:
    - link2-cpp
    - ld-lib-image
    - libjpeg-turbo
    - vimba
    - opencv

  run:
    - link2
    - vimba
    - libjpeg-turbo

test:
  commands:
    - "ld-node-camera-avt-2 --help"

extra:
  git-commit: {{ GIT_FULL_HASH }}

about:
  home: "https://gitlab.com/link.developers/ld-node-camera-avt-2"
  license: "MPL-2.0"
  license_file: "LICENSE"
  summary: "Node to receive feed from Allied Vision GigE cameras."
